[build-menu]
EX_00_LB=_Renumber BASIC program
EX_00_CM=$HOME/scripts/renumBASIC.sh %f %f 10
EX_00_WD=%d
EX_01_LB=Compile assembly program (lwasm)
EX_01_CM=/usr/bin/lwasm --6809 --decb --output=%d/%e.bin %d/%f
EX_01_WD=%d
EX_02_LB=Compile assembly program (asm6809)
EX_02_CM=/usr/local/bin/asm6809 --coco --output=%d/%e.bin %d/%f
EX_02_WD=%d
EX_03_LB=Compile C program (CMOC)
EX_03_CM=/usr/local/bin/cmoc -o %d/%e.bin %d/%f
EX_03_WD=%d
EX_04_LB=Build CoCo 2 DSK image and launch MAME
EX_04_CM=$HOME/scripts/makeDSK-pyDW.sh mame coco2b n
EX_04_WD=%d
EX_05_LB=Build CoCo 2 DSK image and launch MAME (pyDW)
EX_05_CM=$HOME/scripts/makeDSK-pyDW.sh mame coco2b y
EX_05_WD=%d
EX_06_LB=Build CoCo 2 DSK image and launch XRoar
EX_06_CM=$HOME/scripts/makeDSK-pyDW.sh xroar coco2bus n
EX_06_WD=%d
EX_07_LB=Build CoCo 2 DSK image and launch XRoar (pyDW)
EX_07_CM=$HOME/scripts/makeDSK-pyDW.sh xroar coco2bus y
EX_07_WD=%d
EX_08_LB=Build CoCo 2 DSK image and launch trs80gp
EX_08_CM=$HOME/scripts/makeDSK-pyDW.sh trs80gp coco2b n
EX_08_WD=%d
EX_09_LB=Build CoCo 3 DSK image and launch MAME
EX_09_CM=$HOME/scripts/makeDSK-pyDW.sh mame coco3 n
EX_09_WD=%d
EX_10_LB=Build CoCo 3 DSK image and launch MAME (pyDW)
EX_10_CM=$HOME/scripts/makeDSK-pyDW.sh mame coco3 y
EX_10_WD=%d
EX_11_LB=Build CoCo 3 DSK image and launch XRoar
EX_11_CM=$HOME/scripts/makeDSK-pyDW.sh xroar coco3 n
EX_11_WD=%d
EX_12_LB=Build CoCo 3 DSK image and launch XRoar (pyDW)
EX_12_CM=$HOME/scripts/makeDSK-pyDW.sh xroar coco3 y
EX_12_WD=%d
EX_13_LB=Compile ugBasic program, build CoCo 2 DSK image & launch MAME
EX_13_CM=$HOME/scripts/compile-ugBasic-coco.sh %d/%f coco2b mame n
EX_13_CM_WD=%d
EX_14_LB=Compile ugBasic program, build CoCo 2 DSK image & launch XRoar
EX_14_CM=$HOME/scripts/compile-ugBasic-coco.sh %d/%f coco2bus xroar n
EX_14 CM_WD=%d
EX_15_LB=Compile ugBasic program, build CoCo 2 DSK image & launch trs80gp
EX_15_CM=$HOME/scripts/compile-ugBasic-coco.sh %d/%f coco2b trs80gp n
EX_15_CM_WD=%d
EX_16_LB=Compile ugBasic program, build CoCo 3 DSK image & launch MAME
EX_16_CM=$HOME/scripts/compile-ugBasic-coco.sh %d/%f coco3 mame n
EX_16_CM_WD=%d
EX_17_LB=Compile ugBasic program, build CoCo 3 DSK image & launch XRoar
EX_17_CM=$HOME/scripts/compile-ugBasic-coco.sh %d/%f coco3 xroar n
EX_17 CM_WD=%d
EX_18_LB=Create BASIC MC-10 WAV file and launch MAME
EX_18_CM=$HOME/scripts/makeWAV-mc10.sh mc10 mame
EX_18_WD=%d
EX_19_LB=Create BASIC MC-10 WAV file and launch MAME (pyDW)
EX_19_CM=$HOME/scripts/makeWAV-mc10.sh mcx128 mame
EX_19_WD=%d
EX_20_LB=Create BASIC MC-10 WAV file and launch XRoar
EX_20_CM=$HOME/scripts/makeWAV-mc10-XRoar.sh mc10 xroar
EX_20_WD=%d
EX_21_LB=Create BASIC MC-10 WAV file and launch trs80gp
EX_21_CM=$HOME/scripts/makeWAV-mc10.sh mc10 trs80gp
EX_21_WD=%d
EX_22_LB=Compile MC-10 mcbasic program and launch MAME
EX_22_CM=$HOME/scripts/compile-BASIC-mc10.sh %d/%f mame
EX_22_WD=%d
EX_23_LB=Compile MC-10 mcbasic program and launch XRoar
EX_23_CM=$HOME/scripts/compile-BASIC-mc10.sh %d/%f xroar
EX_23_WD=%d
EX_24_LB=Compile MC-10 mcbasic program and launch trs80gp
EX_24_CM=$HOME/scripts/compile-BASIC-mc10.sh %d/%f trs80gp
EX_24_WD=%d
EX_25_LB=Compile BASIC program (FreeBASIC)
EX_25_CM="C:\Program Files\FreeBASIC-1.08.0-win64\fbc.exe" -lang qb %d/%f
EX_25_WD=%d
EX_26_LB=Compile CoCo BASIC-to-6809 program
EX_26_CM=$HOME/scripts/compile-BasTo6809-coco.sh %d/%f
EX_22_WD=%d
